// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJJXiR32JMEtGmWiUGSxpCUtKd99l7xw0',
    appId: '1:7398338226:web:577bec860d109f2c66e3ab',
    messagingSenderId: '7398338226',
    projectId: 'note-app-1a55e',
    authDomain: 'note-app-1a55e.firebaseapp.com',
    storageBucket: 'note-app-1a55e.appspot.com',
    measurementId: 'G-188QXLW821',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaiJRsWGY5VrMWcCXXCMqX6T3B1mFbOZI',
    appId: '1:7398338226:android:eab7addc7e6a9b3266e3ab',
    messagingSenderId: '7398338226',
    projectId: 'note-app-1a55e',
    storageBucket: 'note-app-1a55e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIY2L_W51L-iFOazcW2YUDKA8iPjXwUTI',
    appId: '1:7398338226:ios:8cfd66ad4c227c4966e3ab',
    messagingSenderId: '7398338226',
    projectId: 'note-app-1a55e',
    storageBucket: 'note-app-1a55e.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIY2L_W51L-iFOazcW2YUDKA8iPjXwUTI',
    appId: '1:7398338226:ios:142f79c62343acaa66e3ab',
    messagingSenderId: '7398338226',
    projectId: 'note-app-1a55e',
    storageBucket: 'note-app-1a55e.appspot.com',
    iosBundleId: 'com.example.noteApp.RunnerTests',
  );
}
